name: Parse Telegram Channels (Full Flow)

on:
  schedule:
    # Запуск каждые 30 минут
    - cron: '*/30 * * * *'

  # Возможность запустить вручную
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Run Full Parsing Flow
      run: |
        echo "🚀 Starting complete Telegram parsing flow..."

        # Запуск полного флоу парсинга
        RUN_ONCE=true node run-full-flow.js

        echo "✅ Complete parsing flow finished!"
      env:
        # Supabase
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

        # Groq AI
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

        # Telegram
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}

    - name: Verify Results
      run: |
        echo "🔍 Verifying API results..."

        # Проверяем health endpoint
        curl -s https://rusden-backend.onrender.com/health

        # Проверяем наличие новых данных
        response=$(curl -s https://rusden-backend.onrender.com/api/listings)
        count=$(echo "$response" | jq '.data | // length')

        echo "📊 Current listings count: $count"
        echo "✅ Parsing completed and verified!"